options:
  docker: true
pipelines:
  branches:
    develop:
      - step:
          name: Build
          script:
            - docker build -t ${BITBUCKET_REPO_SLUG} .
            - pipe: atlassian/aws-ecr-push-image:1.2.1
              variables:
                AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
                AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
                AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
                IMAGE_NAME: ${BITBUCKET_REPO_SLUG}
                TAGS: '${BITBUCKET_BRANCH}-${BITBUCKET_BUILD_NUMBER}-${BITBUCKET_COMMIT}'
      - step:
          name: Test
          script: 
            - echo "SKIP TEST FOR NOW . . ."
      - step:
          name: Deploy
          deployment: beta
          image: google/cloud-sdk:latest
          script: 
            - echo $GCLOUD_API_KEYFILE > ~/.gcloud-api-key.json
            - gcloud auth activate-service-account --key-file ~/.gcloud-api-key.json
            - gcloud container clusters get-credentials $K8s_CLUSTER_NAME --zone=$GCLOUD_ZONE --project $GCLOUD_PROJECT_ID
            - kubectl set image deployment/bibit-test bibit-test=$AWS_ECR/${BITBUCKET_REPO_SLUG}:${BITBUCKET_BRANCH}-${BITBUCKET_BUILD_NUMBER}-${BITBUCKET_COMMIT} --record --namespace=$K8s_NAMESPACE